public enum ePrefabType
{
	WALL,
	FLOORPLAN,
	INVALID
}

public enum eMessages
{
	NONE,
	FLOORPLAN_START = 1,
	FLOORPLAN_FADEIN = 2,
	FLOORPLAN_FADEIN_DONE = 3,
	FLOORPLAN_STOP = 10,

	WALL_START = 100,
	WALL_GROW,
	WALL_FULL_HEIGHT,
	WALL_MOUSEOVER,
	WALL_MOUSEEXIT,
	WALL_SELECTED,
	WALL_UNSELECTED,
	WALL_STOP = 110,

	PROGRESS_START = 500,
	PROGRESS_SETPATH,
	PROGRESS_LOAD,
	PROGRESS_CREATE,
	PROGRESS_CONTROLLER,
	PROGRESS_ARTIFACTS,
	PROGRESS_COPYGEO,
	PROGRESS_GEOARTIFACTSREMOVED,
	PROGRESS_REMOVEARTIFACTS,
	PROGRESS_REMOVEARTIFACTS_INFILE,
	PROGRESS_REMOVEARTIFACTS_PROCESS,
	PROGRESS_REMOVEARTIFACTS_SUBTRACT_SEGMENT,
	PROGRESS_REMOVEARTIFACTS_ADD_SEGMENT,
	PROGRESS_REMOVEARTIFACTS_CLOSE,
	PROGRESS_REMOVEARTIFACTS_FIX,

	POINTLINE_CLICK = 600,

	CAMERA_START = 900,
	CAMERA_NEXT,
	CAMERA_PREVIOUS,	
	CAMERA_STOP = 910,

	ALL = 1000
}

public enum eFloorPlanState
{
	IDLE,
	FADEIN,
	FADEOUT,
	END
}

public enum eWallState
{
	IDLE,
	GROW,
	SELECTED,
	END,
}

